### ISSUE TITLE
Issue with creating ip_gen.qsys

### ISSUE THREAD

**Issue by rewingchow1** [cmu-snap/pigasus#5]
When running shell script run_ipgen.sh, I get an error when the command "_qsys-script --script=ip_gen.tcl_" is ran.
![Screen Shot 2021-06-30 at 1 26 09 AM](https://user-images.githubusercontent.com/71918289/123911207-7a24bc80-d949-11eb-887a-e065feaff3d4.png)
![Screen Shot 2021-06-30 at 2 18 55 AM](https://user-images.githubusercontent.com/71918289/123911239-86a91500-d949-11eb-94b0-8b5b2ad04c8a.png)

**Comment by zhipengzhaocmu** [comment]
I just tested with a clean clone of this repo. The script works for me, even with the new DEVICE (1SD110PJ1F43E1VG). 
Could you try to open Quaruts 19.3 in GUI mode to see if you can use "Platform Designer" to create any .qsys. Looks like the first line of ip_gen.tcl "create_system ip_gen" already has problem.

**Comment by rewingchow1** [comment]
Hi Zhipeng,

When running "qsys-script --script=ip_gen.tcl", I get the following error,

***************************************************************
Quartus is a registered trademark of Intel Corporation in the
US and other countries.  Portions of the Quartus Prime software
code, and other portions of the code included in this download
or on this DVD, are licensed to Intel Corporation and are the
copyrighted property of third parties. For license details,
refer to the End User License Agreement at
http://fpgasoftware.intel.com/eula.
***************************************************************

2021.07.06.15:51:56 Warning: Both --quartus-project and --new-quartus-project switches are not used. A new Quartus project named ip_gen will be created using the tcl script filename: /hard_drive/shared/pigasus/hardware/scripts/ip_gen.qpf.
2021.07.06.15:51:56 Info: Doing: qsys-script --script=ip_gen.tcl
2021.07.06.15:52:10 Error: Failed to create Quartus Project, manually re-run the commands included in /hard_drive/shared/pigasus/hardware/scripts/quartus_sh_tcl_file_for_qsyspro.tcl in Quartus tcl shell.

![Screen Shot 2021-07-06 at 3 54 43 PM](https://user-images.githubusercontent.com/71918289/124661398-71fedc80-de75-11eb-8780-3ab2e6ae01d2.png)

When opening through Platform Designer in GUI, I get the same message,

![Screen Shot 2021-07-06 at 4 33 19 PM](https://user-images.githubusercontent.com/71918289/124663339-f0f51480-de77-11eb-8df2-47b56cb1ad95.png)

**Comment by rewingchow1** [comment]
I installed Quartus 19.3 as individual files. Is there a specific method for installation and also could there be a license missing causing this issues. Happens on both Ubuntu 16.04 and 20.04.

**Comment by zhipengzhaocmu** [comment]
Have you installed the "Stratix 10 device support"?

**Comment by rewingchow1** [comment]
Yes, I have. I actually think this is a bug. Will send an update in a bit. When using the GUI and the error message popped up, I closed it and then it continued with creating the project.

**Comment by rewingchow1** [comment]
Have you come across this before?

**Comment by zhipengzhaocmu** [comment]
No I haven't came across this before

**Comment by rewingchow1** [comment]
This is happening on two of my systems both with the same installation methods. Any recommendation on how you guys installed 19.3 on your system? Was it through Individuals files? or a complete package? If individual files, which files were included?

**Comment by zhipengzhaocmu** [comment]
We installed from individual files(Quartus-pro-19.3.0.222-linux.tar and Quartus-pro-19.3.0.222-devices-2.tar) after installing the Quartus, we also installed the device. This has been working on both Ubuntu 16.04 and Ubuntu 18.04. 
Do you have any license issues? Can you manually create any Quartus projects and any .qsys designs (random designs, not Pigasus scripts)?

**Comment by rewingchow1** [comment]
How did you go about installing the device and linking it to the host system? We have a license server setup with our Quartus. I can manually create any Quartus projects, but when creating a project through Platform Designer then that error is thrown, if the project is already created then it is fine. I will try to work around with already created projects.

**Comment by rewingchow1** [comment]
How are your licenses setup? This still happens with your method of installation for 19.3. I am trying a newer version of Quartus 20 or 21. Seems to be a problem with Quartus or License with Platform Designer.

**Comment by zhipengzhaocmu** [comment]
Sorry for the late reply. We use the license serve setup by our school. I never met such issue before. Maybe it is worth posting the problem on Intel's forum as well.

**Comment by rewingchow1** [comment]
This is working fine for me on 20.4, have not tested with full tcl script. Possibly somewhere between 19.4-20.4 it was fixed. Will keep posted for updates. Hopefully the same scripts can work.

**Comment by zhipengzhaocmu** [comment]
We haven't tested Quartus versions other than 19.3. The same scripts may not work for other versions as the naming, IP might be different among different versions of Quartus.

**Comment by rewingchow1** [comment]
I'm hoping 19.4 works as it's not too far off from 19.3.

By the way, I'm a Master's student with the University of Toronto under Professor Paul Chow

**Comment by zhipengzhaocmu** [comment]
Hi Randy,

Nice to meet you! I have a little bit experience of porting to 19.4. If I remembered correctly, the IP names of PCIe was already different from 19.3. If you want to use a different version of Quartus, do expect some glitches in IP generation and composing.

**Comment by rewingchow1** [comment]
So 19.4, does not work. I'm wondering if the script can be adjusted to create a new system but use an already created project. I will have to make minor adjustments to the script and find some kind of work around.

**Comment by rewingchow1** [comment]
I got it to work using this command "qsys-script --quartus-project=ip_gen.qpf  --script=ip_gen.tcl" where I created the project manually.
